# -*- coding: utf-8 -*-
"""building_footprint_unet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naxS6Ak1OUNk5-3MiJn8vdWEIJRzVRqL

# Building Footprint Extraction — U-Net (ResNet backbone)

End-to-end workflow for 4-band aerial imagery:

1. **Rasterize** building footprint shapefile into binary masks aligned to each tile
2. **Chip** 5000×5000 tiles into 512×512 patches
3. **Train** U-Net with a ResNet-34 encoder (`segmentation_models_pytorch`), 4-channel input
4. **Evaluate** with IoU / F1 on a held-out tile split
5. **Inference** on 10 new tiles via sliding window with overlap blending → georeferenced GeoTIFFs
6. **Polygonize** predictions back to vector footprints (GeoPackage)

**Assumptions** (edit the CONFIG cell as needed):
- Training tiles are GeoTIFFs in one folder, inference tiles in another
- All tiles and the shapefile share (or can be reprojected to) the same CRS
- Bands are ordered R, G, B, NIR (order doesn't matter for training as long as it's consistent between train and inference)
"""

# Commented out IPython magic to ensure Python compatibility.
# If needed, install dependencies (uncomment):
# %pip install torch torchvision segmentation-models-pytorch albumentations rasterio geopandas shapely tqdm scikit-learn

import os, glob, math, random, json
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import rasterio
from rasterio import features as rio_features
from rasterio.windows import Window
import geopandas as gpd
from shapely.geometry import shape

import segmentation_models_pytorch as smp
import albumentations as A
from tqdm.auto import tqdm

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

# """## Configuration"""

CONFIG = {
    # ---- paths ----
    "train_tiles_dir":  r"C:\Users\DiSharma\Desktop\Project\LocalMachineCodeTest\Train",        # 36 GeoTIFFs, 5000x5000, 4 bands
    "footprints_shp":   r"C:\Users\DiSharma\Desktop\Project\IndyMapShapefile/IndyBuildingTrain.shp",
    "infer_tiles_dir":  r"C:\Users\DiSharma\Desktop\Project\LocalMachineCodeTest\Test",        # 10 GeoTIFFs for inference
    "work_dir":         r"C:\Users\DiSharma\Desktop\Project\LocalMachineCodeTest\Results",                    # masks, chips, checkpoints, outputs

    # ---- data prep ----
    "patch_size":       512,
    "train_stride":     384,     # overlap during chipping (512 - 384 = 128 px overlap)
    "val_tile_frac":    0.25,    # ~6 of 36 tiles held out for validation (split by TILE)
    "keep_empty_frac":  0.15,    # keep this fraction of building-free patches as negatives

    # ---- normalization ----
    # Set to None to auto-compute per-band mean/std from a sample of training chips
    "band_means":       None,
    "band_stds":        None,

    # ---- model ----
    "encoder":          "resnet34",   # try "resnet50" if you have GPU headroom
    "encoder_weights":  "imagenet",   # smp adapts the first conv for 4 channels
    "in_channels":      4,

    # ---- training ----
    "epochs":           2,
    "batch_size":       8,
    "lr":               1e-4,
    "weight_decay":     1e-4,
    "num_workers":      4,
    "amp":              True,

    # ---- inference ----
    "infer_patch":      512,
    "infer_stride":     256,     # 50% overlap, blended
    "prob_threshold":   0.5,
    "min_building_px":  30,      # drop tiny polygons during vectorization
}

WORK = Path(CONFIG["work_dir"])
for sub in ["masks", "chips/images", "chips/masks", "checkpoints", "predictions"]:
    (WORK / sub).mkdir(parents=True, exist_ok=True)

train_tile_paths = sorted(glob.glob(os.path.join(CONFIG["train_tiles_dir"], "*.tif")))
infer_tile_paths = sorted(glob.glob(os.path.join(CONFIG["infer_tiles_dir"], "*.tif")))
print(f"{len(train_tile_paths)} training tiles | {len(infer_tile_paths)} inference tiles")
assert len(train_tile_paths) > 0, "No training tiles found - check train_tiles_dir"

"""## 1. Rasterize footprints to per-tile masks

For each tile, buildings intersecting its extent are burned into a binary mask (1 = building) using the tile's own transform, so mask and image are pixel-aligned. The shapefile is reprojected to the tile CRS if needed.
"""

gdf_all = gpd.read_file(CONFIG["footprints_shp"])
print(f"{len(gdf_all)} footprint polygons | CRS: {gdf_all.crs}")

# Fix invalid geometries once up front
gdf_all["geometry"] = gdf_all.geometry.buffer(0)
gdf_all = gdf_all[~gdf_all.geometry.is_empty & gdf_all.geometry.notna()]
sindex = None  # built after any reprojection

def rasterize_tile_mask(tile_path, gdf, out_path):
    with rasterio.open(tile_path) as src:
        if gdf.crs != src.crs:
            gdf = gdf.to_crs(src.crs)
        bounds = src.bounds
        # spatial filter: only polygons intersecting this tile
        cand = gdf.cx[bounds.left:bounds.right, bounds.bottom:bounds.top]
        if len(cand) > 0:
            mask = rio_features.rasterize(
                ((geom, 1) for geom in cand.geometry),
                out_shape=(src.height, src.width),
                transform=src.transform,
                fill=0, dtype="uint8", all_touched=False,
            )
        else:
            mask = np.zeros((src.height, src.width), dtype="uint8")
        profile = src.profile.copy()
        profile.update(count=1, dtype="uint8", nodata=None, compress="lzw")
    with rasterio.open(out_path, "w", **profile) as dst:
        dst.write(mask, 1)
    return mask.mean()

mask_dir = WORK / "masks"
coverage = {}
for tp in tqdm(train_tile_paths, desc="Rasterizing masks"):
    out = mask_dir / (Path(tp).stem + "_mask.tif")
    if not out.exists():
        coverage[Path(tp).stem] = rasterize_tile_mask(tp, gdf_all, out)

if coverage:
    vals = np.array(list(coverage.values()))
    print(f"Building pixel fraction per tile — mean {vals.mean():.3f}, min {vals.min():.3f}, max {vals.max():.3f}")

"""## 2. Train / validation split (by tile) and chipping

Splitting by **tile** rather than by patch prevents spatial leakage — neighboring patches from the same tile are nearly identical in appearance, so a random patch-level split would inflate validation scores.
"""

n_val = max(1, round(len(train_tile_paths) * CONFIG["val_tile_frac"]))
shuffled = train_tile_paths.copy()
random.Random(SEED).shuffle(shuffled)
val_tiles   = set(shuffled[:n_val])
train_tiles = set(shuffled[n_val:])
print(f"Train tiles: {len(train_tiles)} | Val tiles: {len(val_tiles)}")
print("Val:", [Path(p).name for p in val_tiles])

def chip_tile(tile_path, mask_path, split, patch, stride, keep_empty_frac, rng):
    """Write image/mask chips as .npy files; returns list of (img_chip, mask_chip, split) records."""
    records = []
    stem = Path(tile_path).stem
    with rasterio.open(tile_path) as img_src, rasterio.open(mask_path) as msk_src:
        H, W = img_src.height, img_src.width
        # positions that cover the full tile, including a final edge-aligned window
        ys = list(range(0, H - patch + 1, stride))
        xs = list(range(0, W - patch + 1, stride))
        if ys[-1] != H - patch: ys.append(H - patch)
        if xs[-1] != W - patch: xs.append(W - patch)
        for y in ys:
            for x in xs:
                win = Window(x, y, patch, patch)
                m = msk_src.read(1, window=win)
                if m.max() == 0 and rng.random() > keep_empty_frac:
                    continue  # subsample empty patches
                im = img_src.read(window=win)  # (4, patch, patch)
                img_name = f"{stem}_{y}_{x}_img.npy"
                msk_name = f"{stem}_{y}_{x}_msk.npy"
                np.save(WORK / "chips/images" / img_name, im)
                np.save(WORK / "chips/masks"  / msk_name, m)
                records.append({"img": img_name, "msk": msk_name, "split": split})
    return records

index_path = WORK / "chips/index.json"
if index_path.exists():
    records = json.loads(index_path.read_text())
    print(f"Loaded existing chip index: {len(records)} chips")
else:
    rng = random.Random(SEED)
    records = []
    for tp in tqdm(train_tile_paths, desc="Chipping"):
        mp = mask_dir / (Path(tp).stem + "_mask.tif")
        split = "val" if tp in val_tiles else "train"
        records += chip_tile(tp, mp, split, CONFIG["patch_size"],
                             CONFIG["train_stride"], CONFIG["keep_empty_frac"], rng)
    index_path.write_text(json.dumps(records))
    print(f"Chipped {len(records)} patches")

n_tr = sum(r["split"] == "train" for r in records)
n_va = sum(r["split"] == "val" for r in records)
print(f"train chips: {n_tr} | val chips: {n_va}")

"""## 3. Normalization statistics

Aerial imagery is often uint8 (0–255) or uint16 (0–65535 / 0–2047). We compute per-band mean/std from a random sample of training chips so normalization is correct regardless of dtype.
"""

if CONFIG["band_means"] is None:
    sample = [r for r in records if r["split"] == "train"]
    sample = random.Random(SEED).sample(sample, min(200, len(sample)))
    acc = []
    for r in sample:
        im = np.load(WORK / "chips/images" / r["img"]).astype(np.float64)
        acc.append(im.reshape(im.shape[0], -1))
    stacked = np.concatenate(acc, axis=1)
    BAND_MEANS = stacked.mean(axis=1)
    BAND_STDS  = stacked.std(axis=1) + 1e-6
else:
    BAND_MEANS = np.array(CONFIG["band_means"], dtype=np.float64)
    BAND_STDS  = np.array(CONFIG["band_stds"], dtype=np.float64)

print("Per-band means:", np.round(BAND_MEANS, 2))
print("Per-band stds: ", np.round(BAND_STDS, 2))

"""## 4. Dataset and augmentation"""

train_aug = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.RandomRotate90(p=0.5),
    A.ShiftScaleRotate(shift_limit=0.05, scale_limit=0.1, rotate_limit=15,
                       border_mode=0, p=0.3),
    A.RandomBrightnessContrast(brightness_limit=0.15, contrast_limit=0.15, p=0.3),
])

class BuildingDataset(Dataset):
    def __init__(self, records, split, augment=False):
        self.recs = [r for r in records if r["split"] == split]
        self.augment = augment

    def __len__(self):
        return len(self.recs)

    def __getitem__(self, i):
        r = self.recs[i]
        img = np.load(WORK / "chips/images" / r["img"]).astype(np.float32)  # (4,H,W)
        msk = np.load(WORK / "chips/masks"  / r["msk"]).astype(np.float32)  # (H,W)

        if self.augment:
            # albumentations expects HWC
            out = train_aug(image=np.moveaxis(img, 0, -1), mask=msk)
            img = np.moveaxis(out["image"], -1, 0)
            msk = out["mask"]

        img = (img - BAND_MEANS[:, None, None]) / BAND_STDS[:, None, None]
        return torch.from_numpy(img.astype(np.float32)), torch.from_numpy(msk)[None, ...]

train_ds = BuildingDataset(records, "train", augment=True)
val_ds   = BuildingDataset(records, "val",   augment=False)

train_dl = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True,
                      num_workers=CONFIG["num_workers"], pin_memory=True, drop_last=True)
val_dl   = DataLoader(val_ds, batch_size=CONFIG["batch_size"], shuffle=False,
                      num_workers=CONFIG["num_workers"], pin_memory=True)
print(len(train_ds), "train |", len(val_ds), "val")

"""## 5. Model — U-Net with ResNet-34 encoder

`segmentation_models_pytorch` adapts the ImageNet-pretrained first conv to 4 input channels (the pretrained RGB weights are reused and the extra channel is initialized sensibly), which typically converges much faster than training from scratch.
"""

model = smp.Unet(
    encoder_name=CONFIG["encoder"],
    encoder_weights=CONFIG["encoder_weights"],
    in_channels=CONFIG["in_channels"],
    classes=1,
).to(DEVICE)

dice_loss = smp.losses.DiceLoss(mode="binary")
bce_loss  = nn.BCEWithLogitsLoss()

def criterion(logits, target):
    return 0.5 * bce_loss(logits, target) + 0.5 * dice_loss(logits, target)

optimizer = torch.optim.AdamW(model.parameters(), lr=CONFIG["lr"],
                              weight_decay=CONFIG["weight_decay"])
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=CONFIG["epochs"])
scaler = torch.cuda.amp.GradScaler(enabled=CONFIG["amp"] and DEVICE == "cuda")

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    tp = fp = fn = tn = 0
    loss_sum, n = 0.0, 0
    for img, msk in loader:
        img, msk = img.to(DEVICE), msk.to(DEVICE)
        with torch.autocast(device_type="cuda", enabled=CONFIG["amp"] and DEVICE == "cuda"):
            logits = model(img)
            loss = criterion(logits, msk)
        loss_sum += loss.item() * img.size(0); n += img.size(0)
        pred = (torch.sigmoid(logits) > 0.5).long()
        t = msk.long()
        _tp, _fp, _fn, _tn = smp.metrics.get_stats(pred, t, mode="binary")
        tp += _tp.sum(); fp += _fp.sum(); fn += _fn.sum(); tn += _tn.sum()
    iou = (tp / (tp + fp + fn + 1e-9)).item()
    f1  = (2 * tp / (2 * tp + fp + fn + 1e-9)).item()
    return loss_sum / max(n, 1), iou, f1

"""## 6. Training loop"""

best_iou = 0.0
history = []
ckpt_best = WORK / "checkpoints/best.pt"

for epoch in range(1, CONFIG["epochs"] + 1):
    model.train()
    running, n = 0.0, 0
    pbar = tqdm(train_dl, desc=f"Epoch {epoch}/{CONFIG['epochs']}")
    for img, msk in pbar:
        img, msk = img.to(DEVICE, non_blocking=True), msk.to(DEVICE, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        with torch.autocast(device_type="cuda", enabled=CONFIG["amp"] and DEVICE == "cuda"):
            logits = model(img)
            loss = criterion(logits, msk)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        running += loss.item() * img.size(0); n += img.size(0)
        pbar.set_postfix(loss=f"{running / n:.4f}")
    scheduler.step()

    val_loss, val_iou, val_f1 = evaluate(model, val_dl)
    history.append({"epoch": epoch, "train_loss": running / n,
                    "val_loss": val_loss, "val_iou": val_iou, "val_f1": val_f1})
    print(f"  val_loss {val_loss:.4f} | IoU {val_iou:.4f} | F1 {val_f1:.4f}")

    if val_iou > best_iou:
        best_iou = val_iou
        torch.save({"model": model.state_dict(),
                    "band_means": BAND_MEANS.tolist(),
                    "band_stds":  BAND_STDS.tolist(),
                    "config": CONFIG}, ckpt_best)
        print(f"  ✔ saved new best (IoU {best_iou:.4f})")

print("Best val IoU:", best_iou)

# Training curves
import matplotlib.pyplot as plt
h = history
fig, ax = plt.subplots(1, 2, figsize=(11, 4))
ax[0].plot([e["epoch"] for e in h], [e["train_loss"] for e in h], label="train")
ax[0].plot([e["epoch"] for e in h], [e["val_loss"] for e in h], label="val")
ax[0].set_title("Loss"); ax[0].legend()
ax[1].plot([e["epoch"] for e in h], [e["val_iou"] for e in h], label="IoU")
ax[1].plot([e["epoch"] for e in h], [e["val_f1"] for e in h], label="F1")
ax[1].set_title("Validation metrics"); ax[1].legend()
plt.tight_layout(); plt.show()

"""## 7. Sanity check — visualize a few validation predictions"""

ckpt = torch.load(WORK / "checkpoints/best.pt", map_location=DEVICE)
model.load_state_dict(ckpt["model"]); model.eval()

idxs = random.sample(range(len(val_ds)), min(4, len(val_ds)))
fig, axes = plt.subplots(len(idxs), 3, figsize=(12, 4 * len(idxs)))
for row, i in enumerate(idxs):
    img_t, msk_t = val_ds[i]
    with torch.no_grad():
        prob = torch.sigmoid(model(img_t[None].to(DEVICE)))[0, 0].cpu().numpy()
    # de-normalize RGB for display
    rgb = (img_t.numpy()[:3] * BAND_STDS[:3, None, None] + BAND_MEANS[:3, None, None])
    rgb = np.clip(rgb / np.percentile(rgb, 99), 0, 1)
    axes[row, 0].imshow(np.moveaxis(rgb, 0, -1)); axes[row, 0].set_title("Image (RGB)")
    axes[row, 1].imshow(msk_t[0], cmap="gray");   axes[row, 1].set_title("Ground truth")
    axes[row, 2].imshow(prob > 0.5, cmap="gray"); axes[row, 2].set_title("Prediction")
    for a in axes[row]: a.axis("off")
plt.tight_layout(); plt.show()

"""## 8. Inference on the 10 tiles — sliding window with overlap blending

Each 5000×5000 tile is processed in 512×512 windows with 50% overlap. Overlapping probabilities are averaged with a cosine-ramp weight (higher confidence at window centers, lower at edges), which removes visible seams. Outputs per tile:
- `*_prob.tif` — float32 probability raster (georeferenced)
- `*_pred.tif` — uint8 binary mask
"""

def make_blend_weight(patch):
    ramp = np.hanning(patch)
    w = np.outer(ramp, ramp).astype(np.float32)
    w = np.clip(w, 1e-3, None)
    return w

@torch.no_grad()
def predict_tile(tile_path, model, out_dir, patch, stride, batch_size=8):
    with rasterio.open(tile_path) as src:
        H, W = src.height, src.width
        profile = src.profile.copy()
        img = src.read().astype(np.float32)  # (4, H, W) — ~400 MB per tile, fits in RAM

    # Ensure img remains float32 after normalization, as BAND_MEANS and BAND_STDS are float64
    img = ((img - BAND_MEANS[:, None, None]) / BAND_STDS[:, None, None]).astype(np.float32)

    prob_acc   = np.zeros((H, W), dtype=np.float32)
    weight_acc = np.zeros((H, W), dtype=np.float32)
    wpatch = make_blend_weight(patch)

    ys = list(range(0, H - patch + 1, stride))
    xs = list(range(0, W - patch + 1, stride))
    if ys[-1] != H - patch: ys.append(H - patch)
    if xs[-1] != W - patch: xs.append(W - patch)
    positions = [(y, x) for y in ys for x in xs]

    for b in tqdm(range(0, len(positions), batch_size),
                  desc=Path(tile_path).stem, leave=False):
        batch_pos = positions[b:b + batch_size]
        batch = np.stack([img[:, y:y+patch, x:x+patch] for (y, x) in batch_pos])
        t = torch.from_numpy(batch).to(DEVICE)
        with torch.autocast(device_type="cuda", enabled=CONFIG["amp"] and DEVICE == "cuda"):
            p = torch.sigmoid(model(t))[:, 0].float().cpu().numpy()
        for (y, x), pi in zip(batch_pos, p):
            prob_acc[y:y+patch, x:x+patch]   += pi * wpatch
            weight_acc[y:y+patch, x:x+patch] += wpatch

    prob = prob_acc / weight_acc
    pred = (prob >= CONFIG["prob_threshold"]).astype("uint8")

    stem = Path(tile_path).stem
    p_prof = profile.copy(); p_prof.update(count=1, dtype="float32", nodata=None, compress="lzw")
    with rasterio.open(out_dir / f"{stem}_prob.tif", "w", **p_prof) as dst:
        dst.write(prob, 1)
    m_prof = profile.copy(); m_prof.update(count=1, dtype="uint8", nodata=None, compress="lzw")
    with rasterio.open(out_dir / f"{stem}_pred.tif", "w", **m_prof) as dst:
        dst.write(pred, 1)
    return prob, pred

pred_dir = WORK / "predictions"
for tp in infer_tile_paths:
    predict_tile(tp, model, pred_dir, CONFIG["infer_patch"], CONFIG["infer_stride"])
print("Done. Rasters written to", pred_dir)

"""## 9. Vectorize predictions to building polygons

Converts each binary raster to polygons, drops slivers below `min_building_px`, applies a light simplify, and writes one GeoPackage with all 10 tiles combined — ready to load in ArcGIS Pro.
"""

all_polys = []
for tp in infer_tile_paths:
    stem = Path(tp).stem
    with rasterio.open(pred_dir / f"{stem}_pred.tif") as src:
        pred = src.read(1)
        transform, crs = src.transform, src.crs
        px_area = abs(transform.a * transform.e)

    for geom, val in rio_features.shapes(pred, mask=pred == 1, transform=transform):
        poly = shape(geom)
        if poly.area / px_area < CONFIG["min_building_px"]:
            continue
        all_polys.append({"geometry": poly, "tile": stem,
                          "area_m2": round(poly.area, 1)})

gdf_pred = gpd.GeoDataFrame(all_polys, crs=crs)
gdf_pred["geometry"] = gdf_pred.geometry.simplify(abs(transform.a) * 0.75)  # ~sub-pixel simplify
out_gpkg = pred_dir / "predicted_footprints.gpkg"
gdf_pred.to_file(out_gpkg, driver="GPKG")
print(f"{len(gdf_pred)} predicted footprints → {out_gpkg}")

"""## Notes & next steps

- **Regularization**: raw CNN polygons have wobbly edges. For cleaner cartographic footprints, consider orthogonalization (e.g., ArcGIS Pro *Regularize Building Footprint* tool, or the `buildingregulariser` Python package).
- **Encoder size**: `resnet34` is a strong baseline; `resnet50` or `efficientnet-b3` may add 1–3 IoU points at higher memory cost.
- **Class imbalance**: if buildings are sparse, try `smp.losses.TverskyLoss(alpha=0.3, beta=0.7)` to penalize missed buildings more.
- **Test-time augmentation**: averaging predictions over flips/rotations (e.g., with the `ttach` package) typically adds ~0.5–1 IoU.
- **Benchmark comparison**: the `*_prob.tif` outputs let you compute PR curves at multiple thresholds, useful when comparing against Blackshark.ai / Living Atlas outputs on the same tiles.
"""